// Curated database of world-class surf spots.
//
// faces  — compass bearing (degrees) looking from the beach OUT to sea.
//          Used to orient the first-person simulation camera, so swell and
//          wind arrive from the correct on-screen direction.
// hand   — which way the wave peels seen from the beach: left, right, or peak (both).
// type   — break type; skill — rough ability level; blurb — one-liner.
const SURF_SPOTS = [
  { id: "pipeline", hand: "left",     name: "Banzai Pipeline",        region: "Oahu, Hawaii",          country: "USA",          lat: 21.6650,  lon: -158.0530, faces: 325, type: "reef",        skill: "expert",       blurb: "The world's most famous wave — a heavy, hollow left over shallow reef." },
  { id: "waimea", hand: "right",       name: "Waimea Bay",             region: "Oahu, Hawaii",          country: "USA",          lat: 21.6420,  lon: -158.0660, faces: 310, type: "big-wave",    skill: "expert",       blurb: "Birthplace of big-wave surfing; breaks properly over 15 ft." },
  { id: "honolua", hand: "right",      name: "Honolua Bay",            region: "Maui, Hawaii",          country: "USA",          lat: 21.0140,  lon: -156.6390, faces: 20,  type: "point",       skill: "advanced",     blurb: "A long, ruler-edged right point that lights up on NW swells." },
  { id: "hanalei", hand: "right",      name: "Hanalei Bay",            region: "Kauai, Hawaii",         country: "USA",          lat: 22.2110,  lon: -159.5000, faces: 10,  type: "point",       skill: "intermediate", blurb: "Long rippable right point framed by jungle cliffs." },
  { id: "mavericks", hand: "right",    name: "Mavericks",              region: "Half Moon Bay, CA",     country: "USA",          lat: 37.4936,  lon: -122.5010, faces: 250, type: "big-wave",    skill: "expert",       blurb: "Cold, jagged and huge — one of the heaviest big waves on Earth." },
  { id: "oceanbeach", hand: "peak",   name: "Ocean Beach",            region: "San Francisco, CA",     country: "USA",          lat: 37.7600,  lon: -122.5130, faces: 265, type: "beach",       skill: "advanced",     blurb: "Shifty, powerful beach break peaks with serious paddle-outs." },
  { id: "trestles", hand: "right",     name: "Lower Trestles",         region: "San Clemente, CA",      country: "USA",          lat: 33.3820,  lon: -117.5880, faces: 215, type: "point",       skill: "intermediate", blurb: "California's high-performance cobblestone playground." },
  { id: "malibu", hand: "right",       name: "Malibu (First Point)",   region: "Malibu, CA",            country: "USA",          lat: 34.0350,  lon: -118.6770, faces: 170, type: "point",       skill: "beginner",     blurb: "The original perfect wave — endless summer right-handers." },
  { id: "rincon", hand: "right",       name: "Rincon",                 region: "Santa Barbara, CA",     country: "USA",          lat: 34.3480,  lon: -119.4750, faces: 195, type: "point",       skill: "intermediate", blurb: "Queen of the Coast — winter W swells peel for hundreds of meters." },
  { id: "huntington", hand: "peak",   name: "Huntington Beach",       region: "Orange County, CA",     country: "USA",          lat: 33.6550,  lon: -118.0050, faces: 215, type: "beach",       skill: "beginner",     blurb: "Surf City USA — consistent pier-side beach break." },
  { id: "puerto", hand: "peak",       name: "Puerto Escondido",       region: "Oaxaca",                country: "Mexico",       lat: 15.8470,  lon: -97.0470,  faces: 190, type: "beach",       skill: "expert",       blurb: "The Mexican Pipeline — the heaviest beach break in the world." },
  { id: "todos", hand: "right",        name: "Todos Santos",           region: "Baja California",       country: "Mexico",       lat: 31.8000,  lon: -116.8000, faces: 280, type: "big-wave",    skill: "expert",       blurb: "Killers — Baja's big-wave island peak on winter NW swells." },
  { id: "pavones", hand: "left",      name: "Pavones",                region: "Golfo Dulce",           country: "Costa Rica",   lat: 8.3970,   lon: -83.1350,  faces: 150, type: "point",       skill: "intermediate", blurb: "One of the longest lefts on the planet when the S swell hits." },
  { id: "puntaroca", hand: "right",    name: "Punta Roca",             region: "La Libertad",           country: "El Salvador",  lat: 13.4810,  lon: -89.3200,  faces: 180, type: "point",       skill: "advanced",     blurb: "Fast, hollow right point — Central America's finest." },
  { id: "chicama", hand: "left",      name: "Chicama",                region: "La Libertad",           country: "Peru",         lat: -7.7000,  lon: -79.4500,  faces: 245, type: "point",       skill: "intermediate", blurb: "Officially the longest left wave in the world — rides over 2 km." },
  { id: "teahupoo", hand: "left",     name: "Teahupo'o",              region: "Tahiti",                country: "Fr. Polynesia",lat: -17.8470, lon: -149.2670, faces: 205, type: "reef",        skill: "expert",       blurb: "The End of the Road — impossibly thick below-sea-level barrels." },
  { id: "cloudbreak", hand: "left",   name: "Cloudbreak",             region: "Tavarua",               country: "Fiji",         lat: -17.8850, lon: 177.1880,  faces: 215, type: "reef",        skill: "expert",       blurb: "World-class left reef that holds from 3 ft to 30 ft." },
  { id: "uluwatu", hand: "left",      name: "Uluwatu",                region: "Bali",                  country: "Indonesia",    lat: -8.8150,  lon: 115.0880,  faces: 230, type: "reef",        skill: "advanced",     blurb: "Bali's iconic cliff-front left — five sections of Indian Ocean juice." },
  { id: "padang", hand: "left",       name: "Padang Padang",          region: "Bali",                  country: "Indonesia",    lat: -8.8110,  lon: 115.1000,  faces: 235, type: "reef",        skill: "expert",       blurb: "The Balinese Pipeline — a short, perfect, shallow left barrel." },
  { id: "gland", hand: "left",        name: "G-Land (Grajagan)",      region: "East Java",             country: "Indonesia",    lat: -8.7480,  lon: 114.3530,  faces: 195, type: "reef",        skill: "advanced",     blurb: "Jungle-backed left that reels down the reef for 300+ meters." },
  { id: "arugam", hand: "right",       name: "Arugam Bay",             region: "Eastern Province",      country: "Sri Lanka",    lat: 6.8400,   lon: 81.8360,   faces: 130, type: "point",       skill: "intermediate", blurb: "Playful sand-bottom right point, best in the SW monsoon season." },
  { id: "jbay", hand: "right",         name: "Jeffreys Bay",           region: "Eastern Cape",          country: "South Africa", lat: -34.0320, lon: 24.9340,   faces: 130, type: "point",       skill: "advanced",     blurb: "Supertubes — arguably the best right-hand point wave anywhere." },
  { id: "skeleton", hand: "left",     name: "Skeleton Bay",           region: "Namib Desert",          country: "Namibia",      lat: -26.6490, lon: 15.1320,   faces: 250, type: "point",       skill: "expert",       blurb: "A freak of sand and fog — minute-long sand-bottom left barrels." },
  { id: "anchor", hand: "right",       name: "Anchor Point",           region: "Taghazout",             country: "Morocco",      lat: 30.5450,  lon: -9.7270,   faces: 250, type: "point",       skill: "intermediate", blurb: "Morocco's flagship right point — long walls on winter NW swells." },
  { id: "nazare", hand: "right",       name: "Nazaré (Praia do Norte)",region: "Leiria",                country: "Portugal",     lat: 39.6050,  lon: -9.0850,   faces: 280, type: "big-wave",    skill: "expert",       blurb: "Home of the biggest waves ever ridden, focused by an undersea canyon." },
  { id: "supertubos", hand: "peak",   name: "Supertubos",             region: "Peniche",               country: "Portugal",     lat: 39.3430,  lon: -9.3620,   faces: 245, type: "beach",       skill: "advanced",     blurb: "The European Pipeline — sand-bottom kegs on the WSL tour." },
  { id: "ericeira", hand: "right",     name: "Ribeira d'Ilhas",        region: "Ericeira",              country: "Portugal",     lat: 38.9940,  lon: -9.4180,   faces: 290, type: "reef",        skill: "intermediate", blurb: "Heart of Europe's first World Surfing Reserve." },
  { id: "mundaka", hand: "left",      name: "Mundaka",                region: "Basque Country",        country: "Spain",        lat: 43.4080,  lon: -2.6990,   faces: 355, type: "river-mouth", skill: "advanced",     blurb: "Legendary river-mouth left — long, hollow and fickle." },
  { id: "hossegor", hand: "peak",     name: "La Gravière",            region: "Hossegor",              country: "France",       lat: 43.6710,  lon: -1.4430,   faces: 275, type: "beach",       skill: "advanced",     blurb: "France's heaviest sandbar — square autumn barrels." },
  { id: "thurso", hand: "right",       name: "Thurso East",            region: "Scotland",              country: "UK",           lat: 58.6010,  lon: -3.5130,   faces: 10,  type: "reef",        skill: "advanced",     blurb: "Cold-water right reef breaking in front of a castle." },
  { id: "bundoran", hand: "left",     name: "The Peak, Bundoran",     region: "County Donegal",        country: "Ireland",      lat: 54.4780,  lon: -8.2830,   faces: 320, type: "reef",        skill: "advanced",     blurb: "Ireland's A-frame reef — cold, green and hollow." },
  { id: "snapper", hand: "right",      name: "Snapper Rocks",          region: "Gold Coast",            country: "Australia",    lat: -28.1620, lon: 153.5500,  faces: 90,  type: "point",       skill: "intermediate", blurb: "Start of the Superbank — kilometre-long sand-bottom rights." },
  { id: "bells", hand: "right",        name: "Bells Beach",            region: "Victoria",              country: "Australia",    lat: -38.3720, lon: 144.2830,  faces: 175, type: "reef",        skill: "intermediate", blurb: "The world's longest-running surf contest venue — the Bells Bowl." },
  { id: "margaret", hand: "left",     name: "Margaret River",         region: "Western Australia",     country: "Australia",    lat: -33.9760, lon: 114.9880,  faces: 250, type: "reef",        skill: "advanced",     blurb: "Main Break — raw Indian Ocean power over granite reef." },
  { id: "noosa", hand: "right",        name: "Noosa Heads",            region: "Queensland",            country: "Australia",    lat: -26.3830, lon: 153.1040,  faces: 45,  type: "point",       skill: "beginner",     blurb: "Five perfect longboard points wrapping around a national park." },
  { id: "raglan", hand: "left",       name: "Manu Bay, Raglan",       region: "Waikato",               country: "New Zealand",  lat: -37.8260, lon: 174.8160,  faces: 290, type: "point",       skill: "intermediate", blurb: "New Zealand's endless left — made famous by Endless Summer." },
  { id: "chiba", hand: "peak",        name: "Ichinomiya (Chiba)",     region: "Kantō",                 country: "Japan",        lat: 35.3750,  lon: 140.3930,  faces: 110, type: "beach",       skill: "intermediate", blurb: "Japan's surf-town heartland and Olympic surfing venue." },
  { id: "byron", hand: "right",        name: "The Pass, Byron Bay",    region: "New South Wales",       country: "Australia",    lat: -28.6370, lon: 153.6280,  faces: 55,  type: "point",       skill: "beginner",     blurb: "Mellow sand-bottom right point — a longboarder's dream." },
];
